baseurl: /zenta
markdown: redcarpet
safe: false
highlighter: pygments
# pygments: true
title: 木娜哥

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
encoding: utf-8

username: angck
name: LA
description:  No Silver Bullet.
url: https://angck.github.io/zenta
